version: '3'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_HOST=backend
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "30000:30000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
